### ISSUE TITLE
'charmap' codec can't encode characters in position 16017-16023: character maps to <undefined>

### ISSUE THREAD

**Issue by sds-osint** [TURROKS/Maltego_WhatsMyName#2]
Running To Online Group on an alias prints the following error once it reaches "soloby.ru"

```
Traceback (most recent call last):
  File "C:\Users\SELF\pytools\_maltegoTransforms\Maltego_WhatsMyName\project.py", line 16, in <module>
    handle_run(__name__, sys.argv, application)
  File "C:\Users\SELFAppData\Roaming\Python\Python312\site-packages\maltego_trx\handler.py", line 25, in handle_run
    print(run_transform(transform_name, client_msg)[0])
  File "C:\Program Files\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 16017-16023: character maps to <undefined>
```

**Comment by sds-osint** [comment]
Added JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8 as an environmental variable and it fixed the issue.
